"""empty message

Revision ID: aded72de6104
Revises: 70bd35b679ca
Create Date: 2024-07-08 00:42:12.237354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aded72de6104'
down_revision = '70bd35b679ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_restaurant_pizzas_restuarant_id_restaurants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), 'restaurants', ['restaurant_id'], ['id'])
        batch_op.drop_column('restuarant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restuarant_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_restaurant_pizzas_restuarant_id_restaurants', 'restaurants', ['restuarant_id'], ['id'])
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
